def changeContents(content):
    content = content.replace("Google-Logo","<img src='Img/Google.png' width=18 height=18>")
    content = content.replace("Amazon-Logo","<img src='Img/Amazon.png' width=16 height=16>")
    content = content.replace("Microsoft-Logo","<img src='Img/Microsoft.jpeg' width=16 height=16>")
    content = content.replace("VMware-Logo","<img src='Img/VMware.jpeg' width=16 height=16>")
    content = content.replace("Indeed-Logo","<img src='Img/Indeed.png' width=19 height=19>")
    content = content.replace("Facebook-Logo","<img src='Img/Facebook.png' width=16 height=16>")
    content = content.replace("AMD-Logo","<img src='Img/AMD.png' width=16 height=16>")
    content = content.replace("Apple-Logo","<img src='Img/Apple.png' width=16 height=16>")
    content = content.replace("Grab-Logo","<img src='Img/Grab.png' width=18 height=18>")
    content = content.replace("PureStorage-Logo","<img src='Img/PureStorage.png' width=16 height=16>")
    content = content.replace("Walmart-Logo","<img src='Img/Walmart.jpeg' width=16 height=16>")
    content = content.replace("Twilio-Logo","<img src='Img/Twilio.png' width=16 height=16>")
    content = content.replace("Arista-Logo","<img src='Img/Arista.jpeg' width=28 height=16>")
    content = content.replace("ByteDance-Logo","<img src='Img/ByteDance.jpg' width=24 height=22>")
    content = content.replace("SnowFlake-Logo","<img src='Img/SnowFlake.png' width=18 height=18>")
    content = content.replace("RedBook-Logo","<img src='Img/RedBook.png' width=18 height=18>")
    content = content.replace("PocketGems-Logo","<img src='Img/PocketGems.png' width=18 height=18>")
    content = content.replace("Schlumberger-Logo","<img src='Img/Schlumberger.jpg' width=40 height=16>")
    content = content.replace("MathWorks-Logo","<img src='Img/MathWorks.gif' width=17 height=17>")
    content = content.replace("LandingAI-Logo","<img src='Img/LandingAI.png' width=17 height=17>")
    content = content.replace("UPenn-Logo","<img src='Img/UPenn.png' width=17 height=17>")
    content = content.replace("Dataminr-Logo","<img src='Img/Dataminr.jpeg' width=17 height=17>")
    content = content.replace("Palo-alto-Logo","<img src='Img/Palo-alto.png' width=20 height=20>")
    content = content.replace("Pony-Logo","<img src='Img/Pony.png' width=30 height=10>")
    content = content.replace("KeepTruckin-Logo","<img src='Img/KeepTruckin.png' width=40 height=20>")
    content = content.replace("Reflexis-Logo","<img src='Img/Reflexis.jpeg' width=20 height=20>")
    content = content.replace("Airbnb-Logo","<img src='Img/Airbnb.png' width=19 height=19>")
    content = content.replace("Alibaba-Logo","<img src='Img/Alibaba.jpeg' width=22 height=19>")
    content = content.replace("DellEMC-Logo","<img src='Img/DellEMC.png' width=18 height=18>")
    content = content.replace("LinkedIn-Logo","<img src='Img/LinkedIn.png' width=18 height=18>")
    content = content.replace("Citi-Logo","<img src='Img/Citi.jpeg' width=22 height=16>")
    content = content.replace("Petuum-Logo","<img src='Img/Petuum.jpeg' width=18 height=18>")
    content = content.replace("Ebay-Logo","<img src='Img/Ebay.png' width=23 height=16>")
    content = content.replace("DXC-Logo","<img src='Img/DXC.png' width=20 height=16>")
    content = content.replace("Cruise-Logo","<img src='Img/Cruise.png' width=22 height=16>")
    content = content.replace("Zhihu-Logo","<img src='Img/Zhihu.jpeg' width=18 height=18>")
    content = content.replace("Momenta-Logo","<img src='Img/Momenta.png' width=20 height=20>")
    content = content.replace("Citadel-Logo","<img src='Img/Citadel.png' width=40 height=18>")
    content = content.replace("Bloomberg-Logo","<img src='Img/Bloomberg.png' width=40 height=16>")
    content = content.replace("Uber-Logo","<img src='Img/Uber.png' width=18 height=18>")
    content = content.replace("Yelp-Logo","<img src='Img/Yelp.png' width=18 height=18>")
    content = content.replace("Salesforce-Logo","<img src='Img/Salesforce.png' width=20 height=16>")
    content = content.replace("Cloudian-Logo","<img src='Img/Cloudian.png' width=18 height=18>")
    content = content.replace("Wayfair-Logo","<img src='Img/Wayfair.png' width=18 height=18>")
    content = content.replace("Tencent-Logo","<img src='Img/Tencent.png' width=18 height=18>")
    content = content.replace("Qualcomm-Logo","<img src='Img/Qualcomm.png' width=18 height=18>")
    content = content.replace("Tripadvisor-Logo","<img src='Img/Tripadvisor.gif' width=18 height=18>")
    content = content.replace("BNYMellon-Logo","<img src='Img/BNYMellon.jpg' width=18 height=18>")
    content = content.replace("Verizon-Logo","<img src='Img/Verizon.png' width=32 height=12>")
    content = content.replace("Comcast-Logo","<img src='Img/Comcast.jpg' width=18 height=18>")
    content = content.replace("Yahoo-Logo","<img src='Img/Yahoo.jpeg' width=18 height=18>")
    content = content.replace("TwoSigma-Logo","<img src='Img/TwoSigma.jpg' width=18 height=18>")
    content = content.replace("ICANN-Logo","<img src='Img/ICANN.png' width=18 height=18>")
    content = content.replace("Wish-Logo","<img src='Img/Wish.png' width=18 height=18>")
    content = content.replace("F5Networks-Logo","<img src='Img/F5Networks.png' width=18 height=18>")
    content = content.replace("Baidu-Logo","<img src='Img/Baidu.png' width=18 height=18>")
    content = content.replace("MorganStanley-Logo","<img src='Img/MorganStanley.png' width=48 height=18>")
    content = content.replace("Kuaishou-Logo","<img src='Img/Kuaishou.png' width=18 height=18>")
    content = content.replace("Goldman-Logo","<img src='Img/Goldman.png' width=48 height=18>")
    content = content.replace("Oracle-Logo","<img src='Img/Oracle.jpeg' height=18>")
    content = content.replace("Meituan-Logo","<img src='Img/Meituan.jpeg' width=18 height=18>")
    content = content.replace("Huawei-Logo","<img src='Img/Huawei.png' width=18 height=18>")
    content = content.replace("PinDuoDuo-Logo","<img src='Img/PinDuoDuo.png' width=18 height=18>")
    content = content.replace("Atlassian-Logo","<img src='Img/Atlassian.jpeg' width=18 height=18>")
    content = content.replace("Compass-Logo","<img src='Img/Compass.jpg' width=48 height=18>")
    content = content.replace("IBM-Logo","<img src='Img/IBM.png' width=16 height=10>")
    content = content.replace("Zoom-Logo","<img src='Img/Zoom.jpeg' width=18 height=18>")
    content = content.replace("Tusimple-Logo","<img src='Img/Tusimple.png' width=18 height=18>")
    content = content.replace("Pinterest-Logo","<img src='Img/Pinterest.jpeg' width=18 height=18>")
    content = content.replace("Paypal-Logo","<img src='Img/Paypal.jpg' width=18 height=18>")
    content = content.replace("Intuit-Logo","<img src='Img/Intuit.png' width=20 height=12>")
    content = content.replace("SAP-Logo","<img src='Img/SAP.png' width=24 height=16>")
    content = content.replace("Akuna-Logo","<img src='Img/Akuna.png' width=28 height=18>")
    content = content.replace("Robinhood-Logo","<img src='Img/Robinhood.png' width=18 height=18>")
    content = content.replace("AMX-Logo","<img src='Img/AMX.png' width=18 height=18>")
    content = content.replace("Avalanche-Logo","<img src='Img/Avalanche.jpeg' width=18")
    content = content.replace("Quora-Logo","<img src='Img/Quora.png' width=16")
    content = content.replace("Kuaishou-Big-Logo","<img src='Img/kuaishou-big.png'  width=128>")
    content = content.replace("Face++-Logo","<img src='Img/Face++.png' height=18>")
    content = content.replace("Snapchat-Logo","<img src='Img/Snapchat.png' height=18>")
    content = content.replace("Instacart-Logo","<img src='Img/Instacart.png' height=18>")
    content = content.replace("Lyft-Logo","<img src='Img/Lyft.png' height=18>")
    content = content.replace("Dropbox-Logo","<img src='Img/Dropbox.png' height=18>")
    content = content.replace("Coinbase-Logo","<img src='Img/Coinbase.svg' height=18>")
    content = content.replace("Doordash-Logo","<img src='Img/Doordash.png' height=18>")
    content = content.replace("Stripe-Logo","<img src='Img/Stripe.png' height=18>")
    content = content.replace("DataBricks-Logo","<img src='Img/Databricks.gif' height=18>")
    content = content.replace("Shopee-Logo","<img src='Img/Shopee.png' height=18>")
    content = content.replace("Instagram-Logo","<img src='Img/Instagram.png' height=18>")
    content = content.replace("JD-Logo","<img src='Img/JD.png' height=18>")
    content = content.replace("Visa-Logo","<img src='Img/Visa.png' height=12>")
    content = content.replace("Tiktok-Logo","<img src='Img/Tiktok.png' height=12>")
    content = content.replace("Niantic-Logo","<img src='Img/Niantic.png' height=12>")
    content = content.replace("TigerGraph-Logo","<img src='Img/TigerGraph.png' height=12>")
    content = content.replace("JumpTrade-Logo","<img src='Img/JumpTrade.jpeg' height=12>")

    content = content.replace("YouXiu-Logo","<img src='Img/YouXiuLogo.png' width=64 height=64>")

    content = content.replace("terms and regulations",'<a href="https://wisdompeak.github.io/lc-score-board/rules.html">terms and regulations</a>')

    content = content.replace("curve-figure","<img src='Img/curve.png'>")

    content = content.replace("<title></title>","<title>残酷刷题群</title>")

    content = content.replace('<head>','<head><link rel="shortcut icon" type="image/x-icon" href="Img/icon.ico" />')

    return content


file = open("index.html", "r") 
content = file.read()
file.close()
content = changeContents(content)
file = open("index.html","w")
file.write(content)
file.close()


file = open("graduates.html", "r") 
content = file.read()
file.close()
content = changeContents(content)
file = open("graduates.html","w")
file.write(content)
file.close()

 

